In [1]:
import os
import matplotlib.pyplot as plt
import cv2
import numpy as np

In [25]:
mask_path = 'C:/Users/sungjoo/Desktop/cf_pred'
image_path = 'C:/Users/sungjoo/Desktop/compression_V1/test/c-spine'
save_path = 'C:/Users/sungjoo/Desktop/save_overlay'

In [28]:
for i in os.listdir(image_path):
    img = cv2.imread(os.path.join(image_path,i),0)
   
    resized_img = cv2.resize(img,(512,512))
    print(resized_img)

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [167 163 156 ... 147 126 130]
 [174 160 158 ... 138 127 132]
 [162 153 144 ... 134 126 142]]
[[ 98  91  84 ... 137 144 158]
 [ 94  81  75 ... 128 133 148]
 [ 83  75  68 ... 118 128 140]
 ...
 [215 210 211 ... 178 178 185]
 [220 209 215 ... 181 188 190]
 [220 219 218 ... 188 191 192]]
[[217 216 219 ... 219 219 219]
 [214 218 213 ... 220 215 220]
 [215 212 212 ... 215 214 214]
 ...
 [242 241 249 ... 250 249 247]
 [241 246 250 ... 250 249 251]
 [239 243 250 ... 250 247 251]]
[[244 248 248 ... 141 147 158]
 [247 244 248 ... 113 117 127]
 [254 251 246 ...  89  94 103]
 ...
 [246 244 247 ... 155 156 164]
 [247 248 246 ... 164 168 171]
 [249 245 248 ... 172 176 178]]
[[195 251 248 ... 229 232 234]
 [176 251 248 ... 242 240 240]
 [236 248 246 ... 244 241 239]
 ...
 [207 204 204 ... 239 241 241]
 [207 209 207 ... 239 239 239]
 [208 207 206 ... 239 240 239]]
[[251 249 249 ... 245 245 245]
 [250 247

[[3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
[[3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
[[3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
[[3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
[[3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
[[3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
[[3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
[[3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
[[3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [

In [36]:
for i,j in zip(os.listdir(mask_path),os.listdir(image_path)):
    msk=os.path.join(mask_path, i)
    msk = cv2.imread(msk, 0)
    img = cv2.imread(os.path.join(image_path, j),0)
    resized = cv2.resize(img,(512,512))
    resized_msk = cv2.resize(msk,(512,512))
    dst = cv2.addWeighted(resized.astype(int), 0.6, resized_msk.astype(int), 0.4, 20)
    cv2.imwrite(os.path.join(save_path,j),dst)