In [1]:
import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
import math

In [2]:
img_path = 'C:\\Users\\sungjoo\\Desktop\\sc_ex\\image'
msk_path = 'C:\\Users\\sungjoo\\Desktop\\sc_ex\\png_label_morph'

In [3]:
org_img_path = 'C:\\Users\\sungjoo\\Desktop\\scoliosis_org\\images'
org_msk_path = 'C:\\Users\\sungjoo\\Desktop\\scoliosis_org\\masks'

In [7]:
#이미지 불러오고 crop한 후 저장하기
save_img_path = 'C:\\Users\\sungjoo\\Desktop\\sc_ex\\crop_image'
save_msk_path = 'C:\\Users\\sungjoo\\Desktop\\sc_ex\\crop_label'

for i,j in zip(os.listdir(img_path),os.listdir(org_img_path)):
    img = os.path.join(img_path,i)
    org_img = cv2.imread(img, 0)
    msk = cv2.imread(os.path.join(msk_path, i), 0)
    print(os.path.join(msk_path, i))
    rect=findcontour(msk)
    
    img2 = os.path.join(org_img_path,i)
    org_images = cv2.imread(img2,0)
    print(org_images)
    org_masks = cv2.imread(os.path.join(org_msk_path,i),0)
    
    msk_dir = os.path.join(save_msk_path, i)
    img_dir = os.path.join(save_img_path, i)
    crop_spine(rect,org_masks, org_images, msk_dir, img_dir)

    

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000001.png
Contours length: 1
boundingRect length: 1
[(619, 79, 623, 1148)]
[[52 50 50 ... 47 47 44]
 [52 53 52 ... 47 48 45]
 [61 57 56 ... 47 49 45]
 ...
 [ 0  0  0 ... 45 44 44]
 [ 0  0  0 ... 45 48 47]
 [ 0  0  0 ... 47 49 51]]
[(619, 79, 623, 1148)]
Give border: (419, -121, 1442, 1427)
Top small: -121
Give border: (419, -121, 1442, 1427)
Top small: -121
[[236 236 238 ...  25  18  20]
 [229 225 225 ...  23  19  20]
 [200 204 198 ...  23  20  21]
 ...
 [182 183 183 ... 155 150 148]
 [188 186 184 ... 152 155 147]
 [188 190 187 ... 152 150 145]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000002.png
Contours length: 1
boundingRect length: 1
[(547, 153, 416, 1798)]
[[101 104 102 ...  85  81  79]
 [101 100 101 ...  82  83  84]
 [101 100 101 ...  84  83  83]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
[(547, 153, 416, 1798)]
Give border: (347, -47, 1163, 2151)
Top 

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000015.png
Contours length: 1
boundingRect length: 1
[(1106, 293, 449, 2629)]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[(1106, 293, 449, 2629)]
Give border: (906, 93, 1755, 3122)
Bottom Big: 3122
Give border: (906, 93, 1755, 3122)
Bottom Big: 3122
[[58 56 57 ... 34 34 33]
 [58 57 59 ... 34 34 34]
 [58 57 60 ... 33 34 34]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000016.png
Contours length: 1
boundingRect length: 1
[(743, 120, 764, 1923)]
[[130 126 129 ...   0   0   0]
 [133 129 129 ...   0   0   0]
 [129 129 129 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
[(743, 120, 764, 1923)]
Give border: (543, -80, 1707, 2243)
Top small: -80
Give border: (543, -80, 1707, 2243)
Top small: -80
[[  0   

[(723, 488, 578, 2685)]
Give border: (523, 288, 1501, 3373)
Give border: (523, 288, 1501, 3373)
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [146 147 139 ... 111 113 118]
 [137 139 131 ... 114 114 118]
 [133 132 130 ... 117 119 126]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000029.png
Contours length: 1
boundingRect length: 1
[(720, 117, 553, 1201)]
[[ 52  50  48 ... 101 105 113]
 [ 51  47  46 ...  97 103 106]
 [ 45  45  44 ...  93  99 103]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
[(720, 117, 553, 1201)]
Give border: (520, -83, 1473, 1518)
Top small: -83
Give border: (520, -83, 1473, 1518)
Top small: -83
[[180 190 190 ... 180 189 188]
 [182 184 186 ... 182 183 187]
 [184 185 182 ... 181 184 181]
 ...
 [232 238 236 ... 155 157 159]
 [232 235 235 ... 153 154 152]
 [234 237 235 ... 152 152 152]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000030.png


C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000042.png
Contours length: 1
boundingRect length: 1
[(466, 0, 666, 1883)]
[[241 233 249 ... 165 167 160]
 [241 235 240 ... 155 151 156]
 [252 252 250 ... 158 163 153]
 ...
 [192 189 176 ... 189 190 183]
 [187 178 179 ... 189 200 202]
 [192 182 190 ... 194 196 191]]
[(466, 0, 666, 1883)]
Give border: (266, -200, 1332, 2083)
Top small: -200
Give border: (266, -200, 1332, 2083)
Top small: -200
[[178 189 184 ... 164 160 168]
 [185 179 179 ... 179 164 176]
 [196 179 195 ... 176 179 164]
 ...
 [178 163 161 ... 145 139 136]
 [169 165 167 ... 154 151 137]
 [178 171 172 ... 160 155 139]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000043.png
Contours length: 1
boundingRect length: 1
[(788, 1138, 624, 3103)]
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [24 23 23 ... 24 26 21]
 [26 24 23 ... 27 25 23]
 [25 23 24 ... 22 25 22]]
[(788, 1138, 624, 3103)]
Give border: (588, 938, 1612, 4441)
Give

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[(533, 448, 746, 2818)]
Give border: (333, 248, 1479, 3466)
Give border: (333, 248, 1479, 3466)
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [ 79  78  77 ... 118 113 116]
 [ 76  75  76 ... 119 113 115]
 [ 76  75  75 ... 122 121 120]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000057.png
Contours length: 1
boundingRect length: 1
[(1032, 153, 683, 1765)]
[[13 13 13 ... 18 19  0]
 [13 13 13 ... 18 19  0]
 [13 13 13 ... 18 19  0]
 ...
 [ 1  2  2 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
[(1032, 153, 683, 1765)]
Give border: (832, -47, 1915, 2118)
Top small: -47
Give border: (832, -47, 1915, 2118)
Top small: -47
[[110 112 115 ...  35  34  33]
 [114 116 117 ...  37  36  35]
 [118 119 119 ...  40  39  38]
 ...
 [172 165 161 ...  98  98  99]
 [173 166 162 ...  99  99  99]
 [174 168 164 

Contours length: 1
boundingRect length: 1
[(988, 12, 523, 1962)]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[(988, 12, 523, 1962)]
Give border: (788, -188, 1711, 2174)
Top small: -188
Give border: (788, -188, 1711, 2174)
Top small: -188
[[  9   8   6 ...  65  66  66]
 [ 10   9   7 ...  65  66  64]
 [ 11  10   8 ...  66  65  63]
 ...
 [176 172 168 ... 147 151 155]
 [178 170 167 ... 146 146 149]
 [174 166 163 ... 148 144 144]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000071.png
Contours length: 1
boundingRect length: 1
[(981, 1026, 610, 3560)]
[[ 33  57  55 ... 112 114 119]
 [ 55 103 101 ... 175 179 187]
 [ 54 101  97 ... 174 175 184]
 ...
 [  0   0   0 ...  74  75  75]
 [  0   0   0 ...  75  75  76]
 [  0   0   0 ...  75  77  77]]
[(981, 1026, 610, 3560)]
Give border: (781, 826, 1791, 4786)
Give border: (781, 826, 1791, 4786)
[[  0   0   0 ...  77  78  75]
 [  0   0   0 ...  77  76  76]
 [  0   

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000084.png
Contours length: 1
boundingRect length: 1
[(868, 37, 570, 1825)]
[[42 42 44 ... 34 32 34]
 [42 38 40 ... 34 32 34]
 [43 40 41 ... 33 31 35]
 ...
 [43 45 44 ...  5  5  5]
 [45 44 44 ...  5  5  5]
 [48 47 44 ...  5  5  5]]
[(868, 37, 570, 1825)]
Give border: (668, -163, 1638, 2062)
Top small: -163
Give border: (668, -163, 1638, 2062)
Top small: -163
[[117 123 117 ...  88  88  91]
 [118 120 125 ...  90  96  94]
 [136 126 133 ...  99  95  96]
 ...
 [120 121 121 ... 149 157 149]
 [128 124 117 ... 156 151 151]
 [127 131 119 ... 147 148 146]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000085.png
Contours length: 1
boundingRect length: 1
[(744, 80, 864, 1695)]
[[ 0  0  0 ...  0  0  0]
 [ 0 32 40 ...  0  0  0]
 [ 0 30 36 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
[(744, 80, 864, 1695)]
Give border: (544, -120, 1808, 1975)
Top small: -120
Give border: (544, -120, 

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000098.png
Contours length: 1
boundingRect length: 1
[(1033, 0, 673, 1744)]
[[26 26 26 ... 58 58 58]
 [26 26 26 ... 59 59 60]
 [26 26 26 ... 61 61 62]
 ...
 [27 27 27 ... 77 77 76]
 [27 27 27 ... 78 78 76]
 [27 27 27 ... 79 79 77]]
[(1033, 0, 673, 1744)]
Give border: (833, -200, 1906, 1944)
Top small: -200
Give border: (833, -200, 1906, 1944)
Top small: -200
[[184 184 185 ... 118 116 115]
 [186 185 185 ... 115 113 112]
 [188 187 187 ... 114 111 110]
 ...
 [152 150 147 ... 165 164 163]
 [150 148 145 ... 165 164 163]
 [149 147 144 ... 163 163 163]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000099.png
Contours length: 1
boundingRect length: 1
[(1053, 44, 632, 1776)]
[[103 106 102 ... 128 143 147]
 [ 99 100  97 ... 131 136 144]
 [ 98 102  92 ... 130 131 132]
 ...
 [ 54  50  54 ...  21  33  29]
 [ 60  55  58 ...  29  33  29]
 [ 65  60  63 ...  28  36  30]]
[(1053, 44, 632, 1776)]
Give border: (853, -156, 1885, 2020)
Top

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000112.png
Contours length: 1
boundingRect length: 1
[(1001, 1503, 877, 2874)]
[[108 107 106 ...  54  54  54]
 [108 108 107 ...  53  53  53]
 [109 108 107 ...  51  51  51]
 ...
 [228 227 225 ... 154 154 154]
 [229 227 225 ... 156 156 156]
 [229 228 225 ... 156 156 156]]
[(1001, 1503, 877, 2874)]
Give border: (801, 1303, 2078, 4577)
Give border: (801, 1303, 2078, 4577)
[[ 75  75  73 ...   0   0   0]
 [ 76  75  73 ...   0   0   0]
 [ 75  73  73 ...   0   0   0]
 ...
 [207 198 208 ... 172 198 174]
 [219 190 182 ... 189 203 209]
 [201 186 164 ... 189 175 177]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000113.png
Contours length: 1
boundingRect length: 1
[(723, 542, 793, 2509)]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[(723, 542, 793, 2509)]
Give border: (523, 342, 1716, 3251)
Give border: (523, 342, 1716, 3251)
[[  0   0   0 ...   0   0   0]

[(692, 28, 491, 1666)]
Give border: (492, -172, 1383, 1894)
Top small: -172
Give border: (492, -172, 1383, 1894)
Top small: -172
[[ 43  43  42 ...  50  49  50]
 [ 47  47  47 ...  51  51  52]
 [ 49  54  53 ...  47  50  52]
 ...
 [172 172 172 ... 219 214 210]
 [172 173 173 ... 223 217 214]
 [177 174 173 ... 224 220 216]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000128.png
Contours length: 1
boundingRect length: 1
[(734, 99, 449, 1796)]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [124 125 124 ...  54  56  63]
 [131 132 132 ...  54  58  62]
 [139 139 139 ...  57  58  63]]
[(734, 99, 449, 1796)]
Give border: (534, -101, 1383, 2095)
Top small: -101
Bottom Big: 2095
Give border: (534, -101, 1383, 2095)
Top small: -101
Bottom Big: 2095
[[ 67  69  69 ...  52  50  50]
 [ 67  69  72 ...  50  47  49]
 [ 70  70  67 ...  49  49  50]
 ...
 [255 255 255 ... 203 207 203]
 [255 255 255 ... 206 206 204]
 [255 255 255 ... 210 211 208]]

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000141.png
Contours length: 1
boundingRect length: 1
[(1051, 895, 689, 3830)]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [111 112 122 ... 160 161 167]
 [114 116 123 ... 157 155 161]
 [117 121 118 ... 157 151 152]]
[(1051, 895, 689, 3830)]
Give border: (851, 695, 1940, 4925)
Give border: (851, 695, 1940, 4925)
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [149 152 149 ... 160 163 162]
 [150 155 157 ... 162 160 150]
 [151 154 155 ... 160 165 154]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000142.png
Contours length: 1
boundingRect length: 1
[(957, 33, 917, 1908)]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[(957, 33, 917, 1908)]
Give border: (757, -167, 2074, 2141)
Top small: -167
Give border: (757, -167, 2074, 2141)
Top small: -167
[[

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000155.png
Contours length: 1
boundingRect length: 1
[(861, 37, 574, 2034)]
[[17 17 17 ...  6  6  6]
 [17 17 17 ...  6  6  6]
 [17 17 17 ...  6  6  6]
 ...
 [92 90 99 ...  7  7  7]
 [87 89 98 ...  7  7  7]
 [91 93 99 ...  7  7  7]]
[(861, 37, 574, 2034)]
Give border: (661, -163, 1635, 2271)
Top small: -163
Give border: (661, -163, 1635, 2271)
Top small: -163
[[ 10  10  10 ...   3   3   3]
 [ 10  10  10 ...   3   3   3]
 [ 10  10  10 ...   3   3   3]
 ...
 [104 101 111 ...  92  90  85]
 [105 108 103 ...  91  91  88]
 [105 102 100 ...  88  89  86]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000156.png
Contours length: 1
boundingRect length: 1
[(661, 1236, 595, 2426)]
[[ 7  7  7 ...  7  6  5]
 [ 7  7  6 ...  9  8  7]
 [ 8  8  7 ...  7  8  8]
 ...
 [52 53 50 ... 40 38 38]
 [54 55 47 ... 39 38 40]
 [50 51 45 ... 40 38 39]]
[(661, 1236, 595, 2426)]
Give border: (461, 1036, 1456, 3862)
Give border: (461, 1036, 1456, 3862)


[(239, 392, 564, 1090)]
Give border: (39, 192, 1003, 1682)
Bottom Big: 1682
Give border: (39, 192, 1003, 1682)
Bottom Big: 1682
[[ 36  37  37 ... 185 185 187]
 [ 36  37  37 ... 191 182 183]
 [ 36  36  36 ... 187 189 190]
 ...
 [ 15  14  14 ...  83  80  78]
 [ 14  16  15 ...  84  82  80]
 [ 15  16  17 ...  86  85  83]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000170.png
Contours length: 1
boundingRect length: 1
[(771, 16, 816, 1877)]
[[59 57 56 ...  7  7  7]
 [57 56 55 ...  8  7  7]
 [56 55 53 ... 10  7  6]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
[(771, 16, 816, 1877)]
Give border: (571, -184, 1787, 2093)
Top small: -184
Give border: (571, -184, 1787, 2093)
Top small: -184
[[ 41  46  44 ...  50  49  48]
 [ 42  48  51 ...  50  49  48]
 [ 45  53  61 ...  49  48  47]
 ...
 [180 178 179 ... 211 209 207]
 [177 177 179 ... 212 210 208]
 [176 176 179 ... 212 211 209]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000171.png
Co

[[117 117 116 ...  67  74  78]
 [116 115 115 ...  65  71  74]
 [113 113 113 ...  62  67  69]
 ...
 [163 162 161 ... 234 234 234]
 [166 166 166 ... 235 234 234]
 [168 169 169 ... 235 234 234]]
[(793, 108, 649, 1703)]
Give border: (593, -92, 1642, 2011)
Top small: -92
Give border: (593, -92, 1642, 2011)
Top small: -92
[[144 145 145 ...  69  69  69]
 [144 145 146 ...  68  69  68]
 [146 147 148 ...  68  68  68]
 ...
 [121 118 116 ... 154 156 155]
 [122 121 119 ... 153 155 154]
 [123 123 122 ... 152 153 153]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000184.png
Contours length: 1
boundingRect length: 1
[(1175, 665, 585, 3727)]
[[200 200 200 ... 147 149 150]
 [197 197 197 ... 146 148 149]
 [191 191 191 ... 144 146 148]
 ...
 [ 13  13  13 ...  30  30  30]
 [ 13  13  13 ...  30  30  30]
 [ 13  13  13 ...  30  30  30]]
[(1175, 665, 585, 3727)]
Give border: (975, 465, 1960, 4592)
Give border: (975, 465, 1960, 4592)
[[  3   5   7 ...  60  58  57]
 [  3   4   6 ...  59  57  55]
 [  

[(329, 463, 411, 1822)]
Give border: (129, 263, 940, 2485)
Give border: (129, 263, 940, 2485)
[[ 25  24  24 ...  30  30  30]
 [ 24  24  24 ...  29  30  31]
 [ 24  24  24 ...  30  30  30]
 ...
 [171 177 174 ... 172 175 176]
 [171 172 175 ... 176 177 172]
 [170 169 172 ... 173 177 170]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000199.png
Contours length: 1
boundingRect length: 1
[(502, 0, 535, 1742)]
[[ 70 103  90 ... 156 160 168]
 [ 89 152 141 ... 235 236 242]
 [ 78 132 120 ... 226 226 228]
 ...
 [184 255 255 ... 255 255 255]
 [185 255 255 ... 253 255 255]
 [184 255 255 ... 254 255 255]]
[(502, 0, 535, 1742)]
Give border: (302, -200, 1237, 1942)
Top small: -200
Give border: (302, -200, 1237, 1942)
Top small: -200
[[132 131 129 ... 149 152 145]
 [207 206 206 ... 226 228 219]
 [199 197 198 ... 214 212 200]
 ...
 [132 139 147 ... 129 125 121]
 [132 136 139 ... 136 128 125]
 [135 134 136 ... 135 133 133]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000200.png
Co

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000212.png
Contours length: 1
boundingRect length: 1
[(675, 593, 621, 2980)]
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ... 50 48 48]
 [ 0  0  0 ... 50 47 48]
 [ 0  0  0 ... 50 48 48]]
[(675, 593, 621, 2980)]
Give border: (475, 393, 1496, 3773)
Give border: (475, 393, 1496, 3773)
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [137 136 132 ... 165 180 190]
 [140 138 133 ... 165 174 184]
 [139 138 132 ... 170 177 181]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000213.png
Contours length: 1
boundingRect length: 1
[(649, 482, 658, 2652)]
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [16 16 16 ...  0  0  0]
 [16 16 16 ...  0  0  0]
 [16 16 16 ...  0  0  0]]
[(649, 482, 658, 2652)]
Give border: (449, 282, 1507, 3334)
Give border: (449, 282, 1507, 3334)
[[  0   0   0 ...   0   0   0]
 [  0

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000227.png
Contours length: 1
boundingRect length: 1
[(253, 321, 417, 1658)]
[[  0   1   2 ...   6   7   7]
 [  0   1   1 ...   6   6   6]
 [  0   1   1 ...   6   6   6]
 ...
 [  0 123 135 ... 128 127 127]
 [  0 119 124 ... 132 131 130]
 [  0 122 121 ... 134 133 133]]
[(253, 321, 417, 1658)]
Give border: (53, 121, 870, 2179)
Give border: (53, 121, 870, 2179)
[[  1   1   1 ...   0   1   1]
 [  1   1   1 ...   1   1   1]
 [  1   1   1 ...   1   1   1]
 ...
 [254   0   0 ... 135 134 134]
 [  0   0   0 ... 136 133 133]
 [  0   0   0 ... 132 132 133]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000228.png
Contours length: 1
boundingRect length: 1
[(976, 19, 421, 1457)]
[[114 117 117 ...  50  52  55]
 [110 113 115 ...  52  54  56]
 [110 108 112 ...  53  56  58]
 ...
 [185 185 183 ... 118 118 114]
 [185 188 188 ... 115 113 110]
 [184 189 189 ... 112 103 101]]
[(976, 19, 421, 1457)]
Give border: (776, -181, 1597, 1676)
Top s

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000240.png
Contours length: 1
boundingRect length: 1
[(961, 98, 517, 1879)]
[[ 19  20  21 ... 102 103 102]
 [ 19  18  18 ... 102 109 114]
 [ 18  16  14 ... 102 101 100]
 ...
 [173 170 164 ...  58  57  56]
 [172 170 165 ...  58  56  55]
 [172 170 166 ...  58  63  66]]
[(961, 98, 517, 1879)]
Give border: (761, -102, 1678, 2177)
Top small: -102
Give border: (761, -102, 1678, 2177)
Top small: -102
[[ 20  19  17 ...  96  92  88]
 [ 20  19  18 ...  97  93  89]
 [ 20  20  19 ...  98  95  91]
 ...
 [161 163 165 ... 124 123 126]
 [164 166 168 ... 122 120 124]
 [167 169 171 ... 121 119 122]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000241.png
Contours length: 1
boundingRect length: 1
[(1058, 57, 480, 1398)]
[[ 6  6  6 ...  0  0  0]
 [ 6  6  6 ...  0  0  0]
 [ 6  6  6 ...  0  0  0]
 ...
 [ 3  3  3 ... 11 11 11]
 [ 3  3  4 ... 11 11 11]
 [ 3  3  4 ... 11 11 11]]
[(1058, 57, 480, 1398)]
Give border: (858, -143, 1738, 1655)
Top

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000254.png
Contours length: 1
boundingRect length: 1
[(569, 413, 671, 3011)]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[(569, 413, 671, 3011)]
Give border: (369, 213, 1440, 3624)
Give border: (369, 213, 1440, 3624)
[[  0   0   0 ...  52  52  52]
 [  0   0   0 ...  50  49  49]
 [  0   0   0 ...  50  48  50]
 ...
 [ 72  76  78 ... 132 129 126]
 [ 73  77  77 ... 130 131 127]
 [ 76  78  78 ... 131 130 125]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000255.png
Contours length: 1
boundingRect length: 1
[(580, 72, 602, 1408)]
[[195 188 192 ...   0   0   0]
 [191 192 188 ...   0   0   0]
 [194 194 191 ...   0   0   0]
 ...
 [  0   0   0 ...  57  59  60]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
[(580, 72, 602, 1408)]
Give border: (380, -128, 1382, 1680)
Top small: -128
Give border: (380, -128, 1382, 1680)
Top small: -128
[[19

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000268.png
Contours length: 1
boundingRect length: 1
[(692, 8, 539, 1722)]
[[211 210 200 ... 188   0   0]
 [214 215 214 ... 180   0   0]
 [210 212 203 ... 179   0   0]
 ...
 [211 211 211 ... 255   0   0]
 [223 222 212 ... 255   0   0]
 [  0   0   0 ...   0   0   0]]
[(692, 8, 539, 1722)]
Give border: (492, -192, 1431, 1930)
Top small: -192
Give border: (492, -192, 1431, 1930)
Top small: -192
[[ 71  64  66 ...  40  41  47]
 [ 78  74  76 ...  36  36  39]
 [ 67  70  76 ...  36  41  41]
 ...
 [130 141 139 ... 156 151 161]
 [143 129 123 ... 157 152 160]
 [135 131 127 ... 163 155 156]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000269.png
Contours length: 1
boundingRect length: 1
[(708, 763, 607, 2392)]
[[10 10  9 ...  9  9 10]
 [ 9  9 10 ...  9  9 10]
 [ 9  9 10 ... 10 10  9]
 ...
 [34 34 35 ... 31 31 32]
 [31 31 32 ... 38 37 40]
 [38 37 40 ... 38 37 41]]
[(708, 763, 607, 2392)]
Give border: (508, 563, 1515, 3355)
Give b

[(976, 19, 421, 1457)]
Give border: (776, -181, 1597, 1676)
Top small: -181
Give border: (776, -181, 1597, 1676)
Top small: -181
[[ 35  40  40 ... 221 222 219]
 [ 35  38  40 ... 218 218 217]
 [ 38  39  39 ... 219 213 211]
 ...
 [ 70  74  75 ... 114 105 105]
 [ 73  73  75 ... 113 110 107]
 [ 77  79  77 ... 113 106 102]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000282.png
Contours length: 1
boundingRect length: 1
[(417, 286, 363, 1626)]
[[  0   0   0 ...  43  42  41]
 [  0   0   0 ...  43  42  44]
 [  0   0   0 ...  42  41  46]
 ...
 [  0   0   0 ... 112 107 103]
 [  0   0   0 ... 121 115 105]
 [  0   0   0 ... 127 123 113]]
[(417, 286, 363, 1626)]
Give border: (217, 86, 980, 2112)
Give border: (217, 86, 980, 2112)
[[57 57 57 ... 50 51 51]
 [58 57 57 ... 50 52 51]
 [59 56 58 ... 50 53 52]
 ...
 [93 94 98 ... 22 22 21]
 [92 94 98 ... 23 24 20]
 [93 93 95 ... 24 24 22]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000283.png
Contours length: 1
boundingRect lengt

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000295.png
Contours length: 1
boundingRect length: 1
[(1158, 1, 588, 1597)]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[(1158, 1, 588, 1597)]
Give border: (958, -199, 1946, 1798)
Top small: -199
Give border: (958, -199, 1946, 1798)
Top small: -199
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [162 166 164 ... 174 178 180]
 [162 165 166 ... 175 176 176]
 [165 167 169 ... 177 175 175]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000296.png
Contours length: 1
boundingRect length: 1
[(429, 52, 664, 2954)]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[(429, 52, 664, 2954)]
Give border: (229, -148, 1293, 3206)
Top small: -148
Bottom Big: 3206
Give border: (229, -148, 1293, 3206)
Top small: -148
Bottom Big: 3206
[[0 0 0 ..

Contours length: 1
boundingRect length: 1
[(976, 19, 421, 1457)]
[[ 57  69  69 ... 100 107  10]
 [ 70  96  95 ... 138 109  23]
 [ 68  95  95 ... 139 106  16]
 ...
 [178 238 238 ... 248 170  29]
 [178 237 237 ... 249 172  29]
 [177 239 237 ... 250 234  42]]
[(976, 19, 421, 1457)]
Give border: (776, -181, 1597, 1676)
Top small: -181
Right big: 1597
Give border: (776, -181, 1597, 1676)
Top small: -181
Right big: 1597
[[ 92  86  88 ... 100 107  10]
 [123 119 118 ... 138 109  23]
 [121 120 121 ... 139 106  16]
 ...
 [131 134 133 ... 149 113  18]
 [127 129 132 ... 150 113  18]
 [125 129 129 ... 149 112  18]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000310.png
Contours length: 1
boundingRect length: 1
[(502, 117, 645, 1694)]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [105 104 105 ...  88  87  80]
 [107 102 101 ...  87  89  86]
 [110 105 104 ...  83  87  89]]
[(502, 117, 645, 1694)]
Give border: (302, -83, 1347, 2011)
Top 

[(965, 0, 635, 1837)]
Give border: (765, -200, 1800, 2037)
Top small: -200
Give border: (765, -200, 1800, 2037)
Top small: -200
[[ 67  68  71 ...  90  83  83]
 [ 67  68  72 ...  87  81  79]
 [ 66  70  75 ...  90  82  75]
 ...
 [140 134 133 ... 149 145 152]
 [144 146 139 ... 148 162 177]
 [136 142 138 ... 169 162 175]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000323.png
Contours length: 1
boundingRect length: 1
[(1133, 579, 598, 3975)]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[(1133, 579, 598, 3975)]
Give border: (933, 379, 1931, 4754)
Give border: (933, 379, 1931, 4754)
[[ 26  27  29 ...  49  52  54]
 [ 26  27  29 ...  49  52  54]
 [ 26  28  29 ...  50  52  55]
 ...
 [226 214 217 ... 178 189 172]
 [208 207 207 ... 166 196 179]
 [209 193 214 ... 166 175 161]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000324.png
Contours length: 1
boundingRect length: 1
[(974, 390, 1047, 3784)]
[

[[ 3  3  3 ...  4  4  4]
 [ 3  3  3 ...  4  5  4]
 [ 3  3  3 ...  4  4  4]
 ...
 [ 3  3  3 ... 62 61 60]
 [ 2  2  3 ... 63 62 61]
 [ 3  3  3 ... 62 63 61]]
[(862, 1274, 684, 3563)]
Give border: (662, 1074, 1746, 5037)
Give border: (662, 1074, 1746, 5037)
[[ 42  46  48 ...   0   0   0]
 [ 42  45  48 ...   0   0   0]
 [ 41  44  46 ...   0   0   0]
 ...
 [202 202 203 ... 188 191 201]
 [202 202 199 ... 193 195 199]
 [198 203 214 ... 197 192 200]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000337.png
Contours length: 1
boundingRect length: 1
[(551, 30, 643, 2069)]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [ 75  68  65 ... 107 107 112]
 [ 70  63  63 ... 115 106 101]
 [ 69  63  61 ... 109 108 108]]
[(551, 30, 643, 2069)]
Give border: (351, -170, 1394, 2299)
Top small: -170
Give border: (351, -170, 1394, 2299)
Top small: -170
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [75 75 81 ... 96 8

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000350.png
Contours length: 1
boundingRect length: 1
[(979, 40, 745, 1730)]
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ... 67 68 68]
 [ 0  0  0 ... 64 65 66]
 [ 0  0  0 ... 62 62 64]]
[(979, 40, 745, 1730)]
Give border: (779, -160, 1924, 1970)
Top small: -160
Give border: (779, -160, 1924, 1970)
Top small: -160
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [187 192 196 ... 164 165 165]
 [184 191 194 ... 163 163 161]
 [181 188 191 ... 159 160 159]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000351.png
Contours length: 1
boundingRect length: 1
[(1027, 991, 670, 3239)]
[[20 20 20 ... 20 20 20]
 [20 20 20 ... 20 20 20]
 [20 20 20 ... 20 20 20]
 ...
 [14 15 15 ... 39 39 38]
 [14 15 15 ... 39 39 38]
 [14 15 15 ... 39 39 39]]
[(1027, 991, 670, 3239)]
Give border: (827, 791, 1897, 4430)
Give border: (827, 791, 1897, 4430)
[[

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000364.png
Contours length: 1
boundingRect length: 1
[(976, 19, 421, 1457)]
[[  0   0   0 ...  42   0   0]
 [  0   0   0 ...  35   0   0]
 [  0   0   0 ...  23   0   0]
 ...
 [  0   0   0 ... 226   0   0]
 [  0   0   0 ... 227   0   0]
 [  0   0   0 ...   0   0   0]]
[(976, 19, 421, 1457)]
Give border: (776, -181, 1597, 1676)
Top small: -181
Give border: (776, -181, 1597, 1676)
Top small: -181
[[138 146 146 ...  53  53  56]
 [110 112 108 ...  42  41  40]
 [ 98  99  88 ...  28  31  29]
 ...
 [156 157 148 ... 160 163 151]
 [155 153 138 ... 159 167 158]
 [160 153 143 ... 160 162 155]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000365.png
Contours length: 1
boundingRect length: 1
[(646, 150, 579, 1473)]
[[147 139 136 ... 109 112 107]
 [142 135 133 ... 105 109 105]
 [130 129 134 ... 106 103  99]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
[(646, 150, 579, 1473)]
Give

[[ 99  99 100 ...  98   1   0]
 [ 97  97  97 ...  96   0   0]
 [ 93  92  92 ...  93   0   0]
 ...
 [ 84  84  84 ...  79   1   0]
 [ 86  86  86 ...  90   1   0]
 [  0   0   0 ...   3   0   0]]
[(826, 848, 818, 3743)]
Give border: (626, 648, 1844, 4791)
Give border: (626, 648, 1844, 4791)
[[ 15  15  15 ...   9   9   9]
 [ 15  15  15 ...   9   9   9]
 [ 15  15  15 ...   9   9   9]
 ...
 [180 179 178 ... 200 200 200]
 [180 178 177 ... 199 199 199]
 [181 178 176 ... 197 198 198]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000378.png
Contours length: 1
boundingRect length: 1
[(1344, 0, 668, 1689)]
[[105  95  84 ...  76   0   2]
 [105  96  84 ...  76   0   2]
 [105  96  84 ...  76   0   2]
 ...
 [ 13  13  13 ...   0   0   0]
 [ 17  17  17 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
[(1344, 0, 668, 1689)]
Give border: (1144, -200, 2212, 1889)
Top small: -200
Give border: (1144, -200, 2212, 1889)
Top small: -200
[[157 152 147 ... 143 150 153]
 [157 153 149 ... 142 147 153]
 [

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000391.png
Contours length: 1
boundingRect length: 1
[(1053, 1, 685, 2054)]
[[ 6  6  5 ... 10 10 10]
 [ 6  5  5 ... 10 10 10]
 [ 6  5  5 ... 10 10 10]
 ...
 [ 0  0  0 ... 23 21 20]
 [ 0  0  0 ... 23 22 22]
 [ 0  0  0 ... 23 24 23]]
[(1053, 1, 685, 2054)]
Give border: (853, -199, 1938, 2255)
Top small: -199
Give border: (853, -199, 1938, 2255)
Top small: -199
[[  9  11  12 ...  16  16  16]
 [  9  10  12 ...  17  17  17]
 [  8  10  14 ...  18  18  18]
 ...
 [121 122 126 ... 135 139 140]
 [121 121 126 ... 132 139 140]
 [119 117 123 ... 135 139 140]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000392.png
Contours length: 1
boundingRect length: 1
[(940, 65, 614, 1705)]
[[14 16 15 ... 65 59 55]
 [12 13 13 ... 64 65 68]
 [10 11 11 ... 59 61 64]
 ...
 [ 0  0  0 ...  2  2  1]
 [ 0  0  0 ...  3  4  2]
 [ 0  0  0 ...  6  7  6]]
[(940, 65, 614, 1705)]
Give border: (740, -135, 1754, 1970)
Top small: -135
Give border: (740, -135, 

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000405.png
Contours length: 1
boundingRect length: 1
[(925, 119, 526, 1791)]
[[0 0 0 ... 1 0 0]
 [0 0 0 ... 2 0 1]
 [0 0 0 ... 3 0 2]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[(925, 119, 526, 1791)]
Give border: (725, -81, 1651, 2110)
Top small: -81
Give border: (725, -81, 1651, 2110)
Top small: -81
[[  0   1   1 ...   5   1   0]
 [  0   0   1 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [120 117 120 ...  87  86  85]
 [116 114 118 ...  87  86  85]
 [121 119 122 ...  87  87  86]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000406.png
Contours length: 1
boundingRect length: 1
[(555, 557, 1507, 3122)]
[[237 204 226 ...  35  35  35]
 [228 210 207 ...  35  35  35]
 [211 225 227 ...  33  33  33]
 ...
 [189 189 189 ... 102 102 102]
 [190 190 190 ... 108 108 108]
 [191 191 190 ...  70  70  70]]
[(555, 557, 1507, 3122)]
Give border: (355, 357, 2262, 3879)
Give border: (355, 357, 2262, 3879)
[[15

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000419.png
Contours length: 1
boundingRect length: 1
[(1043, 104, 459, 1947)]
[[ 72  82  87 ... 227 230   0]
 [ 68  73  78 ... 225 229   0]
 [ 65  66  75 ... 222 231   0]
 ...
 [142 134 134 ... 215 216   0]
 [156 155 160 ... 217 217   0]
 [  0   0   0 ...   0   0   0]]
[(1043, 104, 459, 1947)]
Give border: (843, -96, 1702, 2251)
Top small: -96
Bottom Big: 2251
Give border: (843, -96, 1702, 2251)
Top small: -96
Bottom Big: 2251
[[237 243 243 ... 234 237 240]
 [237 230 241 ... 233 231 238]
 [234 227 236 ... 225 233 234]
 ...
 [255 255 253 ... 246 246 245]
 [255 255 255 ... 255 255 255]
 [  0   0   0 ...   0   0   0]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000420.png
Contours length: 1
boundingRect length: 1
[(647, 45, 560, 1559)]
[[172 171 173 ...   4   4   0]
 [167 171 176 ...   4   4   0]
 [164 169 172 ...   4   4   0]
 ...
 [ 72  71  72 ...  13  15   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0  

[[123 119 118 ...   0   0   0]
 [117 116 115 ...   0   0   0]
 [117 116 110 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
[(524, 30, 674, 1693)]
Give border: (324, -170, 1398, 1923)
Top small: -170
Give border: (324, -170, 1398, 1923)
Top small: -170
[[182 179 179 ... 185 180 187]
 [177 180 177 ... 185 184 187]
 [176 179 170 ... 175 177 183]
 ...
 [163 156 159 ... 178 184 185]
 [155 160 161 ... 173 184 182]
 [159 167 165 ... 180 177 182]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000434.png
Contours length: 1
boundingRect length: 1
[(268, 254, 740, 2744)]
[[ 54  53  52 ...  33  18   1]
 [ 53  52  51 ...  32  19   1]
 [ 51  51  49 ...  31  20   0]
 ...
 [187 175 169 ... 137  77   0]
 [186 176 169 ... 138  82   0]
 [182 175 173 ... 133 147   0]]
[(268, 254, 740, 2744)]
Give border: (68, 54, 1208, 3198)
Bottom Big: 3198
Give border: (68, 54, 1208, 3198)
Bottom Big: 3198
[[ 12  12  12 ...   0   0   0]
 [ 1

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000447.png
Contours length: 1
boundingRect length: 1
[(1028, 10, 880, 3498)]
[[160 159 159 ... 204   0   0]
 [156 155 155 ... 198   1   1]
 [148 148 149 ... 189   3   2]
 ...
 [ 11  11  11 ...  10   3   2]
 [ 14  13  12 ...  10   2   0]
 [  4   3   1 ...   0   3   3]]
[(1028, 10, 880, 3498)]
Give border: (828, -190, 2108, 3708)
Top small: -190
Give border: (828, -190, 2108, 3708)
Top small: -190
[[ 77  77  77 ... 121 121 122]
 [ 71  71  71 ... 115 115 115]
 [ 62  62  62 ... 102 103 104]
 ...
 [181 176 172 ... 148 148 149]
 [180 176 172 ... 147 148 149]
 [184 181 178 ... 144 145 147]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000448.png
Contours length: 1
boundingRect length: 1
[(1024, 140, 884, 3359)]
[[  0   0   0 ... 203   4   4]
 [  0   0   0 ... 192   0   0]
 [  0   0   0 ... 177   0   0]
 ...
 [  0   0   0 ...   8   2   1]
 [  0   0   0 ...   9   2   1]
 [  0   0   0 ...   4   3   3]]
[(1024, 140, 884, 3359)]


C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000461.png
Contours length: 1
boundingRect length: 1
[(913, 0, 581, 1675)]
[[ 7  7  7 ...  0  0  0]
 [30 34 32 ...  0  0  0]
 [29 27 28 ...  0  0  0]
 ...
 [ 3  3  3 ... 35 35 34]
 [ 2  2  2 ... 36 34 32]
 [ 1  1  1 ... 37 30 35]]
[(913, 0, 581, 1675)]
Give border: (713, -200, 1694, 1875)
Top small: -200
Give border: (713, -200, 1694, 1875)
Top small: -200
[[ 30  30  30 ...  29  30  29]
 [122 159 152 ... 116 114 114]
 [128 138 137 ... 126 122 126]
 ...
 [161 161 161 ... 175 175 171]
 [165 162 158 ... 179 180 173]
 [166 165 160 ... 188 184 176]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000462.png
Contours length: 1
boundingRect length: 1
[(1003, 19, 532, 1952)]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[(1003, 19, 532, 1952)]
Give border: (803, -181, 1735, 2171)
Top small: -181
Give border: (803, -181, 1735, 2171)
Top small: -181
[[ 28  2

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [15 14 16 ...  0  0  0]
 [14 12 15 ...  0  0  0]
 [15 13 17 ...  0  0  0]]
[(976, 19, 421, 1457)]
Give border: (776, -181, 1597, 1676)
Top small: -181
Give border: (776, -181, 1597, 1676)
Top small: -181
[[191 188 161 ...   0   0   0]
 [191 183 181 ...   0   0   0]
 [167 156 187 ...   0   0   0]
 ...
 [ 50  51  55 ...  36  38  41]
 [ 47  51  53 ...  34  39  44]
 [ 49  51  51 ...  35  40  45]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000476.png
Contours length: 1
boundingRect length: 1
[(545, 601, 886, 3908)]
[[ 81  81  78 ...  64  59  58]
 [ 81  74  72 ...  63  57  57]
 [ 73  72  67 ...  63  58  56]
 ...
 [156 160 166 ...  27  23  24]
 [167 170 177 ...  25  25  24]
 [170 176 179 ...  28  27  24]]
[(545, 601, 886, 3908)]
Give border: (345, 401, 1631, 4709)
Give border: (345, 401, 1631, 4709)
[[174 170 164 ...  13  13  13]
 [162 168 167 ...  13  13  13]
 [163 175 170 ...  13  13  13]
 ...
 [ 

[(916, 49, 620, 1807)]
Give border: (716, -151, 1736, 2056)
Top small: -151
Give border: (716, -151, 1736, 2056)
Top small: -151
[[ 27  30  28 ...  80  81  73]
 [ 28  29  27 ...  79  81  78]
 [ 29  30  26 ...  83  82  78]
 ...
 [142 149 147 ... 156 147 138]
 [148 146 135 ... 151 141 144]
 [137 141 143 ... 156 152 150]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000490.png
Contours length: 1
boundingRect length: 1
[(933, 0, 606, 2007)]
[[ 2  2  2 ...  4  4  4]
 [ 2  2  2 ...  4  4  4]
 [ 2  2  2 ...  4  4  4]
 ...
 [ 1  1  1 ... 62 65 75]
 [ 1  1  1 ... 74 70 72]
 [ 1  1  1 ... 79 81 70]]
[(933, 0, 606, 2007)]
Give border: (733, -200, 1739, 2207)
Top small: -200
Give border: (733, -200, 1739, 2207)
Top small: -200
[[  1   1   0 ...  43  43  43]
 [  2   2   1 ...  49  40  53]
 [  6   7   6 ...  55  64  72]
 ...
 [110 113 110 ... 116 124 120]
 [ 98  95 108 ... 118 124 106]
 [ 81  83  99 ... 119 113 104]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000491.png
Con

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000503.png
Contours length: 1
boundingRect length: 1
[(398, 0, 527, 2881)]
[[18 18 18 ... 18 18 18]
 [18 18 18 ... 18 18 18]
 [18 18 18 ... 18 18 18]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
[(398, 0, 527, 2881)]
Give border: (198, -200, 1125, 3081)
Top small: -200
Bottom Big: 3081
Give border: (198, -200, 1125, 3081)
Top small: -200
Bottom Big: 3081
[[18 18 18 ... 97 95 94]
 [18 18 18 ... 96 96 95]
 [18 18 18 ... 96 95 95]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000504.png
Contours length: 1
boundingRect length: 1
[(992, 1069, 666, 3466)]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[(992, 1069, 666, 3466)]
Give border: (792, 869, 1858, 4735)
Give border: (792, 869, 1858, 4735)
[[ 90  99 104 ...   4   3   3]
 [ 90  98 1

[(553, 0, 507, 1927)]
Give border: (353, -200, 1260, 2127)
Top small: -200
Give border: (353, -200, 1260, 2127)
Top small: -200
[[143 145 144 ... 144 149 152]
 [142 143 142 ... 147 150 152]
 [137 139 139 ... 151 150 152]
 ...
 [171 166 165 ... 151 150 144]
 [168 164 164 ... 137 138 136]
 [166 161 164 ... 129 133 132]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000518.png
Contours length: 1
boundingRect length: 1
[(483, 0, 664, 1864)]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [ 95  95  96 ...  48  48  48]
 [105 105 106 ...  48  48  48]
 [118 119 122 ...  48  48  49]]
[(483, 0, 664, 1864)]
Give border: (283, -200, 1347, 2064)
Top small: -200
Give border: (283, -200, 1347, 2064)
Top small: -200
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [84 82 79 ... 93 93 90]
 [82 81 79 ... 93 94 91]
 [82 80 78 ... 94 93 90]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000519.png
Cont

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000532.png
Contours length: 1
boundingRect length: 1
[(903, 710, 1873, 4137)]
[[  0   0   0 ... 210 214   1]
 [  0   0   0 ... 215 208   0]
 [  0   0   0 ... 208 207   1]
 ...
 [ 61  62  62 ...   0   0   0]
 [ 61  62  62 ...   0   0   0]
 [ 61  62  62 ...   0   0   0]]
[(903, 710, 1873, 4137)]
Give border: (703, 510, 2976, 5047)
Right big: 2976
Give border: (703, 510, 2976, 5047)
Right big: 2976
[[  0   0   0 ... 218 219   2]
 [  0   0   0 ... 220 219   2]
 [  0   0   0 ... 218 219   3]
 ...
 [229 221 209 ...   1   1   1]
 [227 223 209 ...   1   1   1]
 [215 211 213 ...   1   1   1]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000533.png
Contours length: 1
boundingRect length: 1
[(69, 719, 1700, 4275)]
[[205 206 209 ...   0   0   0]
 [204 211 217 ...   0   0   0]
 [213 215 216 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
[(69, 719, 1700, 4275)]
Gi

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000546.png
Contours length: 1
boundingRect length: 1
[(1049, 0, 496, 2059)]
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [30 29 29 ...  3  3  2]
 [29 27 27 ...  3  2  1]
 [25 27 21 ...  7  0  0]]
[(1049, 0, 496, 2059)]
Give border: (849, -200, 1745, 2259)
Top small: -200
Give border: (849, -200, 1745, 2259)
Top small: -200
[[  0   0   0 ...  20  20  20]
 [  4   2   4 ...  78  81  71]
 [  1   1   1 ...  79  75  72]
 ...
 [126 123 122 ... 136 125 117]
 [125 122 116 ... 127 119 117]
 [130 125 115 ... 120 117 117]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000547.png
Contours length: 1
boundingRect length: 1
[(1238, 0, 540, 1887)]
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [23 23 24 ...  2  1  1]
 [23 23 25 ...  3  2  1]
 [23 24 26 ...  3  3  1]]
[(1238, 0, 540, 1887)]
Give border: (1038, -200, 1978, 2087)
Top small: -200
Give border: (1038, -200

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000561.png
Contours length: 1
boundingRect length: 1
[(530, 0, 546, 1851)]
[[198 201 202 ... 172 186 193]
 [197 193 207 ... 184 188 193]
 [204 194 197 ... 201 187 189]
 ...
 [209 211 199 ... 139 152 140]
 [205 203 206 ... 145 143 137]
 [197 202 210 ... 141 139 140]]
[(530, 0, 546, 1851)]
Give border: (330, -200, 1276, 2051)
Top small: -200
Give border: (330, -200, 1276, 2051)
Top small: -200
[[203 197 202 ... 213 202 202]
 [196 201 206 ... 201 201 193]
 [205 211 199 ... 204 209 189]
 ...
 [155 154 164 ... 170 169 170]
 [152 155 167 ... 176 174 176]
 [160 158 172 ... 179 181 190]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000562.png
Contours length: 1
boundingRect length: 1
[(530, 0, 817, 1809)]
[[ 51  59  57 ...  39  43   7]
 [ 62  80  76 ...  50  45  12]
 [ 62  79  76 ...  51  47  11]
 ...
 [ 68  91  90 ... 177 131  29]
 [ 69  94  94 ... 180 131  29]
 [ 70  95  96 ... 182 177  38]]
[(530, 0, 817, 1809)]
Give borde

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000575.png
Contours length: 1
boundingRect length: 1
[(1295, 1201, 357, 1513)]
[[213 213 212 ... 224 220   0]
 [215 217 214 ... 219 217   0]
 [216 213 216 ... 218 218   0]
 ...
 [243 241 240 ... 251 250   0]
 [240 238 238 ... 253 252   1]
 [238 241 237 ... 253 250   0]]
[(1295, 1201, 357, 1513)]
Give border: (1095, 1001, 1852, 2914)
Bottom Big: 2914
Give border: (1095, 1001, 1852, 2914)
Bottom Big: 2914
[[158 165 163 ... 235 239 240]
 [157 162 165 ... 233 234 237]
 [156 161 164 ... 230 236 230]
 ...
 [ 38  36  36 ... 182 180 174]
 [ 37  34  35 ... 182 181 180]
 [ 37  33  32 ... 186 185 182]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000576.png
Contours length: 1
boundingRect length: 1
[(918, 799, 725, 3732)]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[(918, 799, 725, 3732)]
Give border: (718, 599, 1843, 4731)
Give border: (718, 599, 1843, 

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000589.png
Contours length: 1
boundingRect length: 1
[(1084, 0, 582, 1704)]
[[63 63 62 ...  0  0  0]
 [63 63 62 ...  0  0  0]
 [63 63 62 ...  0  0  0]
 ...
 [ 0  0  0 ... 10 14 18]
 [ 0  0  0 ...  6  9 13]
 [ 0  0  0 ...  3  4  7]]
[(1084, 0, 582, 1704)]
Give border: (884, -200, 1866, 1904)
Top small: -200
Give border: (884, -200, 1866, 1904)
Top small: -200
[[134 134 132 ...  85  84  84]
 [133 134 132 ...  78  80  81]
 [132 134 131 ...  69  72  75]
 ...
 [180 183 186 ... 157 154 153]
 [177 179 184 ... 160 158 156]
 [173 176 183 ... 164 162 160]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000590.png
Contours length: 1
boundingRect length: 1
[(1029, 0, 638, 1572)]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  7   7   6 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [255 255 255 ... 255 255 255]]
[(1029, 0, 638, 1572)]
Give border: (829, -200, 1867, 1772)
Top s

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000603.png
Contours length: 1
boundingRect length: 1
[(635, 30, 494, 2350)]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[(635, 30, 494, 2350)]
Give border: (435, -170, 1329, 2580)
Top small: -170
Give border: (435, -170, 1329, 2580)
Top small: -170
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [137 136 136 ... 145 140 148]
 [129 128 133 ... 138 138 139]
 [123 124 128 ... 143 138 138]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000604.png
Contours length: 1
boundingRect length: 1
[(434, 0, 538, 1522)]
[[255 255 255 ... 220 213 215]
 [255 255 255 ... 203 204 201]
 [253 255 249 ... 185 190 188]
 ...
 [ 63  66  61 ...   0   0   0]
 [ 70  69  65 ...   0   0   0]
 [ 68  71  70 ...   0   0   0]]
[(434, 0, 538, 1522)]
Give border: (234, -200, 1172, 1722)
Top small: -200
Give border: (234, -200, 11

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000617.png
Contours length: 1
boundingRect length: 1
[(726, 0, 617, 3833)]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [194 194 194 ... 211 210 210]
 [195 195 196 ... 212 210 209]
 [197 197 197 ... 212 210 209]]
[(726, 0, 617, 3833)]
Give border: (526, -200, 1543, 4033)
Top small: -200
Bottom Big: 4033
Give border: (526, -200, 1543, 4033)
Top small: -200
Bottom Big: 4033
[[ 12  13  13 ...   6   5   3]
 [ 12  14  14 ...   7   5   4]
 [ 12  14  16 ...   9   7   7]
 ...
 [199 202 203 ... 204 203 202]
 [198 199 200 ... 201 201 201]
 [197 197 197 ... 199 200 202]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000618.png
Contours length: 1
boundingRect length: 1
[(879, 0, 894, 2315)]
[[210 213 215 ...  16  22  27]
 [205 207 210 ...  15  21  26]
 [208 208 207 ...  13  20  25]
 ...
 [  4   4   4 ...  68  71  74]
 [  4   4   4 ...  68  70  71]
 [  4   4   4 ...  67  72  75]

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000630.png
Contours length: 1
boundingRect length: 1
[(815, 1327, 1035, 1555)]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[(815, 1327, 1035, 1555)]
Give border: (615, 1127, 2050, 3082)
Give border: (615, 1127, 2050, 3082)
[[ 88  88  88 ... 183 185 186]
 [ 88  89  89 ... 185 185 185]
 [ 88  89  89 ... 186 186 183]
 ...
 [111 111 106 ... 110 110 108]
 [114 114 109 ... 112 112 109]
 [113 114 109 ... 112 111 109]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000631.png
Contours length: 1
boundingRect length: 1
[(713, 1255, 981, 1743)]
[[195 201 208 ...   0   0   0]
 [195 196 193 ...   0   0   0]
 [196 187 174 ...   0   0   0]
 ...
 [ 23  23  23 ...   0   0   0]
 [ 24  24  24 ...   0   0   0]
 [  3   3   3 ...   0   0   0]]
[(713, 1255, 981, 1743)]
Give border: (513, 1055, 1894, 3198)
Give border: (513, 1055, 1894, 3198)
[[198 191 192 ...  38  38 

 [ 0  0  0 ...  0  0  0]]
[(763, 28, 484, 1374)]
Give border: (563, -172, 1447, 1602)
Top small: -172
Give border: (563, -172, 1447, 1602)
Top small: -172
[[ 64  66  67 ...  45  45  46]
 [ 58  60  63 ...  46  44  45]
 [ 52  56  58 ...  50  48  48]
 ...
 [123 124 119 ...  81  83  82]
 [126 124 116 ...  81  80  84]
 [122 122 116 ...  77  77  80]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000644.png
Contours length: 1
boundingRect length: 1
[(976, 19, 421, 1457)]
[[24 26 29 ...  0  0  0]
 [27 30 34 ...  0  0  0]
 [30 31 34 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
[(976, 19, 421, 1457)]
Give border: (776, -181, 1597, 1676)
Top small: -181
Right big: 1597
Give border: (776, -181, 1597, 1676)
Top small: -181
Right big: 1597
[[115 115 119 ...   0   0   0]
 [112 109 108 ...   0   0   0]
 [111 106 103 ...   0   0   0]
 ...
 [130 131 132 ...  33  36  36]
 [129 128 132 ...  34  35  36]
 [132 132 135 ...  35  36  36]]
C:\Users\su

 [0 0 0 ... 0 0 0]]
[(1188, 966, 461, 3158)]
Give border: (988, 766, 1849, 4324)
Give border: (988, 766, 1849, 4324)
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [220 222 223 ... 223 218 226]
 [220 221 223 ... 227 221 226]
 [223 225 220 ... 223 226 226]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000658.png
Contours length: 1
boundingRect length: 1
[(608, 82, 421, 1708)]
[[122 119 116 ... 134 143   0]
 [118 115 113 ... 131 136   0]
 [113 112 111 ... 126 129   0]
 ...
 [108 113 102 ... 195 213   0]
 [113 109 112 ... 201 212   1]
 [  2   0   1 ...   2   1   0]]
[(608, 82, 421, 1708)]
Give border: (408, -118, 1229, 1990)
Top small: -118
Give border: (408, -118, 1229, 1990)
Top small: -118
[[143 145 149 ... 111 113 114]
 [147 147 146 ... 117 116 115]
 [152 150 143 ... 118 117 116]
 ...
 [141 133 141 ... 170 172 165]
 [137 141 145 ... 167 174 167]
 [136 147 142 ... 168 173 170]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morp

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000671.png
Contours length: 1
boundingRect length: 1
[(990, 261, 640, 1606)]
[[173 170 168 ... 231 234 235]
 [170 166 162 ... 235 232 235]
 [165 161 161 ... 234 231 229]
 ...
 [ 22  21  19 ...  44  26   0]
 [ 21  19  19 ...  48  37   9]
 [ 19  16  17 ...  49  46  24]]
[(990, 261, 640, 1606)]
Give border: (790, 61, 1830, 2067)
Give border: (790, 61, 1830, 2067)
[[ 11  12  10 ... 127 120 117]
 [  9  11  11 ... 130 124 118]
 [  6   7   9 ... 125 122 119]
 ...
 [ 97  99 102 ... 107 110 111]
 [ 98  99 100 ... 107 106 105]
 [ 99  97 100 ... 107 105 104]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000672.png
Contours length: 1
boundingRect length: 1
[(976, 19, 421, 1457)]
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 7  7  7 ... 25 25 25]
 [ 7  8  8 ... 25 24 23]
 [ 7  8  9 ... 26 25 24]]
[(976, 19, 421, 1457)]
Give border: (776, -181, 1597, 1676)
Top small: -181
Give border: (776, -181

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000685.png
Contours length: 1
boundingRect length: 1
[(161, 39, 577, 1483)]
[[ 58  58  48 ... 193 198 207]
 [ 66  62  46 ... 173 173 176]
 [ 72  70  53 ... 155 150 147]
 ...
 [255 255 252 ... 147 151 160]
 [255 250 255 ... 157 156 164]
 [255 251 245 ... 173 163 184]]
[(161, 39, 577, 1483)]
Give border: (-39, -161, 938, 1722)
Left small: -39
Top small: -161
Give border: (-39, -161, 938, 1722)
Left small: -39
Top small: -161
[[ 58  58  48 ...  58  65  70]
 [ 66  62  46 ...  40  41  43]
 [ 72  70  53 ...  20  18  18]
 ...
 [178 177 171 ... 158 170 168]
 [183 179 174 ... 157 169 170]
 [176 181 176 ... 156 166 175]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000686.png
Contours length: 1
boundingRect length: 1
[(380, 124, 575, 1577)]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [103 104 103 ... 123 123 125]
 ...
 [152 146 141 ... 196 195 192]
 [156 148 141 ... 193 194 192]
 [159 150 142 ... 196 196 193]

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000699.png
Contours length: 1
boundingRect length: 1
[(976, 19, 421, 1457)]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [ 53  52  55 ... 104 103  97]
 [ 54  53  57 ... 109 107 100]
 [ 63  61  65 ... 121 130 107]]
[(976, 19, 421, 1457)]
Give border: (776, -181, 1597, 1676)
Top small: -181
Give border: (776, -181, 1597, 1676)
Top small: -181
[[  6   7   8 ...  17  17  17]
 [ 18  18  31 ...  30  40  37]
 [ 24  29  35 ...  65  68  68]
 ...
 [109 104  99 ... 137 143 148]
 [104 106 100 ... 139 144 148]
 [ 98  99  99 ... 136 138 143]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000700.png
Contours length: 1
boundingRect length: 1
[(976, 19, 421, 1457)]
[[ 14  13  11 ...  51  55  59]
 [ 15  14  11 ...  52  55  60]
 [ 12  11  10 ...  49  52  57]
 ...
 [152 152 146 ... 148 150 145]
 [149 147 141 ... 152 156 152]
 [146 145 142 ... 151 158 159]]
[(976, 19, 421, 1457)]
Give b

[[ 87  87  87 ... 111   2   1]
 [ 85  85  84 ... 105   0   0]
 [ 80  80  80 ...  95   0   0]
 ...
 [ 51  49  47 ...  44   1   0]
 [ 47  49  51 ...  44   0   0]
 [  0   0   0 ...   0   0   0]]
[(976, 19, 421, 1457)]
Give border: (776, -181, 1597, 1676)
Top small: -181
Give border: (776, -181, 1597, 1676)
Top small: -181
[[ 83  83  84 ... 208 212 214]
 [ 82  82  82 ... 216 217 215]
 [ 78  78  78 ... 213 215 217]
 ...
 [146 144 142 ... 153 153 153]
 [146 143 141 ... 153 153 153]
 [146 147 148 ... 152 151 150]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000713.png
Contours length: 1
boundingRect length: 1
[(976, 19, 421, 1457)]
[[124 119 112 ...  86  90  88]
 [120 115 110 ...  88  94  90]
 [117 112 108 ...  91  97  92]
 ...
 [180 186 192 ... 154 151 144]
 [189 194 198 ... 153 148 141]
 [191 197 202 ... 148 144 136]]
[(976, 19, 421, 1457)]
Give border: (776, -181, 1597, 1676)
Top small: -181
Give border: (776, -181, 1597, 1676)
Top small: -181
[[205 201 195 ...  88  83  78]
 [

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000726.png
Contours length: 1
boundingRect length: 1
[(976, 19, 421, 1457)]
[[ 64  64  64 ... 152   0   0]
 [ 62  62  62 ... 147   0   0]
 [ 58  58  59 ... 137   0   0]
 ...
 [148 148 148 ... 136   0   0]
 [152 152 152 ... 139   6   3]
 [  1   1   1 ...   0   0   0]]
[(976, 19, 421, 1457)]
Give border: (776, -181, 1597, 1676)
Top small: -181
Give border: (776, -181, 1597, 1676)
Top small: -181
[[ 83  82  81 ... 228 226 224]
 [ 78  78  78 ... 227 226 224]
 [ 72  72  72 ... 225 224 223]
 ...
 [125 126 126 ...  87  87  87]
 [125 128 129 ...  85  86  88]
 [127 128 129 ...  85  87  88]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000727.png
Contours length: 1
boundingRect length: 1
[(976, 19, 421, 1457)]
[[ 23  22  20 ... 156 163 166]
 [ 23  22  20 ... 155 162 166]
 [ 23  22  20 ... 153 161 166]
 ...
 [  1   1   1 ... 180 185 187]
 [  1   1   1 ... 180 185 187]
 [  1   1   1 ... 180 185 187]]
[(976, 19, 421, 1457)]
Give b

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000740.png
Contours length: 1
boundingRect length: 1
[(1278, 49, 529, 1565)]
[[17 15 11 ...  0  0  0]
 [18 15 11 ...  0  0  0]
 [18 15 11 ...  0  0  0]
 ...
 [ 7  7  7 ...  0  0  0]
 [ 8  8  8 ...  0  0  0]
 [ 8  8  8 ...  0  0  0]]
[(1278, 49, 529, 1565)]
Give border: (1078, -151, 2007, 1814)
Top small: -151
Give border: (1078, -151, 2007, 1814)
Top small: -151
[[199 200 200 ... 169 163 159]
 [196 195 194 ... 168 163 160]
 [193 188 186 ... 167 164 162]
 ...
 [162 160 157 ... 157 156 156]
 [165 162 157 ... 163 161 159]
 [170 162 154 ... 165 164 162]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000741.png
Contours length: 1
boundingRect length: 1
[(976, 19, 421, 1457)]
[[  3   2   0 ... 166   0   0]
 [  3   2   0 ... 161   0   0]
 [  3   1   0 ... 153   0   0]
 ...
 [ 22  22  22 ...  14   5   3]
 [ 24  24  24 ...  16   0   0]
 [  4   4   4 ...   0   0   0]]
[(976, 19, 421, 1457)]
Give border: (776, -181, 1597, 1676)
T

C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000753.png
Contours length: 1
boundingRect length: 1
[(643, 462, 553, 2738)]
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ... 78 77  0]
 [ 0  0  0 ... 80 79  0]
 [ 0  0  0 ... 79 79  0]]
[(643, 462, 553, 2738)]
Give border: (443, 262, 1396, 3400)
Give border: (443, 262, 1396, 3400)
[[  0   0   0 ... 113 115 106]
 [  0   0   0 ... 114 112 103]
 [  0   0   0 ... 117 115 105]
 ...
 [139 140 141 ... 169 166 163]
 [138 141 146 ... 165 163 157]
 [137 140 146 ... 169 166 164]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000754.png
Contours length: 1
boundingRect length: 1
[(833, 39, 428, 1931)]
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ... 30 30 36]
 [ 0  0  0 ... 31 33 40]
 [ 0  0  0 ... 31 34 40]]
[(833, 39, 428, 1931)]
Give border: (633, -161, 1461, 2170)
Top small: -161
Bottom Big: 2170
Give border: (633, -161, 1461, 2170)
Top

[(976, 19, 421, 1457)]
Give border: (776, -181, 1597, 1676)
Top small: -181
Give border: (776, -181, 1597, 1676)
Top small: -181
[[  0   0   0 ...   0   3   4]
 [  0   0   0 ...   2   0   0]
 [ 40  38  38 ...   0   0   0]
 ...
 [ 23  22  24 ... 119 124 120]
 [ 21  21  24 ... 115 119 119]
 [ 19  19  20 ... 122 123 128]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000767.png
Contours length: 1
boundingRect length: 1
[(976, 19, 421, 1457)]
[[10 10 10 ...  0  0  0]
 [ 9  9 10 ...  0  0  0]
 [ 9 10 11 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
[(976, 19, 421, 1457)]
Give border: (776, -181, 1597, 1676)
Top small: -181
Give border: (776, -181, 1597, 1676)
Top small: -181
[[  2   4   3 ... 128 122 121]
 [  6   6   4 ... 127 125 123]
 [  8   7   5 ... 129 129 123]
 ...
 [185 183 185 ... 187 191 186]
 [184 180 183 ... 191 185 184]
 [186 180 183 ... 193 186 185]]
C:\Users\sungjoo\Desktop\sc_ex\png_label_morph\HIRA20_SC_000768.png
C

In [5]:
# #contour 후 이미지 crop
# def crop_spine(threshold_img, org_img, msk_dir, img_dir):
#     contours, _ = cv2.findContours(threshold_img.astype(np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    

#     print("Contours length: " + str(len(contours)))
#     rect = [cv2.boundingRect(cnt) for cnt in contours]
#     print("boundingRect length: " + str(len(contours)))
#     print(rect)
    

#     crop_img = ''
#     for i, (x, y, w, h) in enumerate(rect):
#         left, top, right, bottom = x, y, x+w, y+h
#         crop_msk = crop(threshold_img, give_border((left, top, right, bottom),200,threshold_img.shape, True))
#         crop_img = crop(org_img, give_border((left, top, right, bottom),50,threshold_img.shape, True))

#         print(crop_img)
# #         plt.imshow(crop_img, cmap='gray') 
    
#     cv2.imwrite(msk_dir, crop_msk)
#     cv2.imwrite(img_dir, crop_img)

#     # return crop_img


In [4]:
#contour 후 이미지 crop
def findcontour(threshold_img):
    contours, _ = cv2.findContours(threshold_img.astype(np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    

    print("Contours length: " + str(len(contours)))
    rect = [cv2.boundingRect(cnt) for cnt in contours]
    print("boundingRect length: " + str(len(contours)))
    print(rect)
    return rect
    
def crop_spine(rect, threshold_img, org_img, msk_dir, img_dir):
    crop_img = ''
    print(rect)
    for i, (x, y, w, h) in enumerate(rect):
        left, top, right, bottom = x, y, x+w, y+h
        crop_msk = crop(threshold_img, give_border((left, top, right, bottom),200,threshold_img.shape, True))
        crop_img = crop(org_img, give_border((left, top, right, bottom),200,threshold_img.shape, True))

        print(crop_img)
#         plt.imshow(crop_img, cmap='gray') 
    
#     cv2.imwrite(msk_dir, crop_msk)
#     cv2.imwrite(img_dir, crop_img)

    # return crop_img


In [5]:
#찾은 좌표 바탕으로 이미지 crop
def crop(image, coords, border=0, logging=False):
    # coords should be a tuple with (x1, y1, x2, y2)
    if logging:
        print("Shape of image: " + str(shape(image)))
    left, top, right, bottom = coords

    if isinstance(image, np.ndarray):
        return image[top: bottom, left: right]
    else:
        return image.crop((left, top, right, bottom))

In [6]:
#찾은 좌표 바탕으로 boarder 넓히기
def give_border(coords, border, shp, logging=False):
    flag = False
    coords = coords[0]-border, coords[1]-border, coords[2]+border, coords[3]+border

    if logging:
        print("Give border: " + str(coords))

    if coords[0] < 0:
        print("Left small: " + str(coords[0]))
        coords = (0, coords[1], coords[2], coords[3])
        flag = True
    if coords[1] < 0:
        print("Top small: " + str(coords[1]))
        coords = (coords[0], 0, coords[2], coords[3])
        flag = True

    if coords[2] > shp[1]:
        print("Right big: " + str(coords[2]))
        coords = (coords[0], coords[1], shp[1], coords[3])
        flag = True

    if coords[3] > shp[0]:
        print("Bottom Big: " + str(coords[3]))
        coords = (coords[0], coords[1], coords[2], shp[0])
        flag = True

    # if flag == False:
    #     print("Nothing has changed in give border")
    return coords