In [32]:
from __future__ import print_function
from __future__ import absolute_import

import os
import sys
import glob
import json
import re
import shutil
from shutil import copytree, ignore_patterns
import numpy as np
import cv2


In [41]:
input_path = 'C:/Users/sungjoo/Desktop/2nd_dataset/dataset/test/images/'
output_path = 'C:/Users/sungjoo/Desktop/2nd_dataset/dataset/pngdataset/test_img/'

In [42]:
for i in os.listdir(input_path):
    img = os.path.join(input_path,i)
    img_jpg = cv2.imread(img,0)
    print(img_jpg)
    print(output_path)
    cv2.imwrite(output_path + i[:-4]+'.png',img_jpg)

[[244 249 249 ... 246 251 245]
 [247 255 252 ... 246 247 241]
 [243 252 249 ... 240 242 240]
 ...
 [103 209 234 ... 249 247 245]
 [108 212 234 ... 249 247 245]
 [111 215 234 ... 249 247 245]]
C:/Users/sungjoo/Desktop/2nd_dataset/dataset/pngdataset/test_img/
[[ 99 140 130 ... 255 253 252]
 [177 230 225 ... 252 251 251]
 [196 236 237 ... 245 249 253]
 ...
 [150 239 247 ... 243 245 246]
 [173 238 253 ... 245 246 247]
 [165 250 250 ... 245 247 248]]
C:/Users/sungjoo/Desktop/2nd_dataset/dataset/pngdataset/test_img/
[[245 227 224 ... 248 246 243]
 [187 226 227 ... 248 250 252]
 [158 228 227 ... 247 247 249]
 ...
 [234 229 221 ... 248 250 250]
 [227 230 227 ... 245 245 243]
 [222 223 207 ... 243 242 240]]
C:/Users/sungjoo/Desktop/2nd_dataset/dataset/pngdataset/test_img/
[[126 245 255 ... 197 199 200]
 [125 245 255 ... 191 194 196]
 [124 243 255 ... 189 193 196]
 ...
 [238 238 237 ... 247 246 239]
 [238 238 238 ... 249 251 242]
 [239 238 238 ... 250 254 237]]
C:/Users/sungjoo/Desktop/2nd_datas